# Generated by Django 6.0.6 on 2026-07-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='goals',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='reviewer',
            field=models.CharField(default='HR Manager', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')]),
        ),
    ]
