# Generated by Django 6.0.6 on 2026-07-03 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_name',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Resume', 'Resume'), ('Offer Letter', 'Offer Letter'), ('ID Proof', 'ID Proof'), ('Certificate', 'Certificate'), ('Experience Letter', 'Experience Letter')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Sample Document', max_length=150),
            preserve_default=False,
        ),
    ]
